version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_er
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: escola_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_er
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exemplo.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
